---
version: "3"
services:
  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - default   
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    expose:
      - 5601
    ports:
      - "5601:5601"
    networks:
      - default   
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    hostname: mosquitto    
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    expose:
      - 1883
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - default      
  adapter:
    build: .
    command: node app.js
    depends_on:
      - elasticsearch
      - mosquitto
    networks:
      - default         
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24      
